-- AUTO-GENERATED by scripts/build-schema.mjs
-- 不要直接编辑;改 server/apps/<name>/schema.sql


-- ============================================================
-- 系统应用表 (无前缀)
-- ============================================================

-- ==================== chat ====================
-- 对话:会话 + 消息。系统级,无 app_ 前缀。
CREATE TABLE conversations (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_conversations_updated ON conversations(updated_at DESC);

CREATE TABLE messages (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  message         TEXT NOT NULL,
  meta            TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_messages_conv ON messages(conversation_id, id);

-- ==================== collab ====================
-- 协作:AI 授权 token。系统级,无 app_ 前缀。
CREATE TABLE tokens (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  token         TEXT NOT NULL UNIQUE,
  scope         TEXT NOT NULL DEFAULT 'read',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  last_used_at  TEXT
);
CREATE INDEX idx_tokens_token ON tokens(token);

-- ==================== settings ====================
-- 设置:全局 KV。系统级,无 app_ 前缀。
-- 存:AI 模型 url/key/model、动态默认 icon/cover 等。
CREATE TABLE settings (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);


-- ============================================================
-- 上下文应用表 (app_<name>_*)
-- ============================================================

-- ==================== accounts ====================
-- 网络账号:在各平台的身份/链接(不存密码,密码归 vault)。
CREATE TABLE app_accounts_services (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL DEFAULT '',
  username    TEXT NOT NULL DEFAULT '',
  email       TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_accounts_services_created ON app_accounts_services(created_at DESC);

-- ==================== apikeys ====================
-- 各种服务的 API key。
CREATE TABLE app_apikeys_items (
  id          TEXT PRIMARY KEY,
  service     TEXT NOT NULL,
  name        TEXT NOT NULL DEFAULT '',
  api_key     TEXT NOT NULL DEFAULT '',
  scope       TEXT NOT NULL DEFAULT '',
  expire_at   TEXT,
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_apikeys_items_expire ON app_apikeys_items(expire_at);

-- ==================== apps ====================
-- App 清单:在用的软件和服务。
CREATE TABLE app_apps_items (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  platform    TEXT NOT NULL DEFAULT '',
  category    TEXT NOT NULL DEFAULT '',
  url         TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'using',
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== articles ====================
-- 文章:自己发表的文章索引(标题、链接、来源、发表日期、摘要、封面)。
CREATE TABLE app_articles_items (
  id           TEXT PRIMARY KEY,
  title        TEXT NOT NULL,
  url          TEXT NOT NULL DEFAULT '',
  source       TEXT NOT NULL DEFAULT '',
  summary      TEXT NOT NULL DEFAULT '',
  published_at TEXT,
  cover        TEXT,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_articles_items_published ON app_articles_items(published_at DESC);

-- ==================== assets ====================
-- 资产/负债。amount 用"分"存储。
CREATE TABLE app_assets_items (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  kind        TEXT NOT NULL DEFAULT 'asset',
  category    TEXT NOT NULL DEFAULT '',
  amount      INTEGER NOT NULL DEFAULT 0,
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_assets_items_kind ON app_assets_items(kind);

-- ==================== bookmarks ====================
-- Bookmarks:收藏的链接。
CREATE TABLE app_bookmarks_items (
  id          TEXT PRIMARY KEY,
  url         TEXT NOT NULL,
  title       TEXT,
  description TEXT,
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_bookmarks_items_created ON app_bookmarks_items(created_at DESC);

-- ==================== books ====================
-- Books:想读 / 在读 / 读过的书。
CREATE TABLE app_books_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  author      TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'want',
  rating      INTEGER NOT NULL DEFAULT 0,
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_books_items_status_created ON app_books_items(status, created_at DESC);

-- ==================== calendar ====================
-- 日程:一条一条带日期(可选时间)的事项。
CREATE TABLE app_calendar_events (
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  date       TEXT NOT NULL,
  time       TEXT,
  note       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_calendar_events_date ON app_calendar_events(date);

-- ==================== cards ====================
-- 银行卡。type ∈ { debit, credit }。
CREATE TABLE app_cards_items (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  bank        TEXT NOT NULL DEFAULT '',
  card_number TEXT NOT NULL DEFAULT '',
  type        TEXT NOT NULL DEFAULT 'debit',
  expire      TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_cards_items_created ON app_cards_items(created_at DESC);

-- ==================== concerts ====================
-- 演唱会。
CREATE TABLE app_concerts_shows (
  id            TEXT PRIMARY KEY,
  artist        TEXT NOT NULL,
  tour          TEXT NOT NULL DEFAULT '',
  venue         TEXT NOT NULL DEFAULT '',
  city          TEXT NOT NULL DEFAULT '',
  show_date     TEXT,
  ticket_price  INTEGER NOT NULL DEFAULT 0,
  seat          TEXT NOT NULL DEFAULT '',
  rating        INTEGER NOT NULL DEFAULT 0,
  note          TEXT NOT NULL DEFAULT '',
  cover         TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_concerts_shows_date ON app_concerts_shows(show_date DESC);

-- ==================== contacts ====================
-- 通讯录:联系人。
CREATE TABLE app_contacts_people (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  nickname    TEXT NOT NULL DEFAULT '',
  phone       TEXT NOT NULL DEFAULT '',
  email       TEXT NOT NULL DEFAULT '',
  company     TEXT NOT NULL DEFAULT '',
  title       TEXT NOT NULL DEFAULT '',
  address     TEXT NOT NULL DEFAULT '',
  birthday    TEXT,
  note        TEXT NOT NULL DEFAULT '',
  avatar      TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_contacts_people_name ON app_contacts_people(name);

-- ==================== devices ====================
-- 设备:在用的硬件。
CREATE TABLE app_devices_items (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  category      TEXT NOT NULL DEFAULT '',
  brand         TEXT NOT NULL DEFAULT '',
  model         TEXT NOT NULL DEFAULT '',
  serial        TEXT NOT NULL DEFAULT '',
  purchased_at  TEXT,
  price         INTEGER NOT NULL DEFAULT 0,
  note          TEXT NOT NULL DEFAULT '',
  cover         TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_devices_items_category ON app_devices_items(category);

-- ==================== docs ====================
-- 证件库:身份证、护照、驾照等。明文存储(单机自部署设计选择)。
CREATE TABLE app_docs_items (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  number      TEXT NOT NULL DEFAULT '',
  issuer      TEXT NOT NULL DEFAULT '',
  issued_at   TEXT,
  expire_at   TEXT,
  image_front TEXT,
  image_back  TEXT,
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_docs_items_expire ON app_docs_items(expire_at);

-- ==================== domains ====================
-- 域名:记录持有的域名、注册商、过期日期。
CREATE TABLE app_domains_items (
  id          TEXT PRIMARY KEY,
  domain      TEXT NOT NULL,
  registrar   TEXT NOT NULL DEFAULT '',
  expire_date TEXT,
  status      TEXT NOT NULL DEFAULT 'active',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_domains_items_expire ON app_domains_items(expire_date);

-- ==================== emails ====================
-- 邮箱地址簿。
CREATE TABLE app_emails_addresses (
  id         TEXT PRIMARY KEY,
  address    TEXT NOT NULL,
  label      TEXT NOT NULL DEFAULT '',
  provider   TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_emails_addresses_created ON app_emails_addresses(created_at DESC);

-- ==================== exhibitions ====================
-- 展览。
CREATE TABLE app_exhibitions_visits (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  venue       TEXT NOT NULL DEFAULT '',
  city        TEXT NOT NULL DEFAULT '',
  visited_at  TEXT,
  rating      INTEGER NOT NULL DEFAULT 0,
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_exhibitions_visits_at ON app_exhibitions_visits(visited_at DESC);

-- ==================== feed ====================
-- 动态:你和 AI 共写的时间线。author 区分谁写的。
CREATE TABLE app_feed_posts (
  id          TEXT PRIMARY KEY,
  author      TEXT NOT NULL DEFAULT 'user',
  content     TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_feed_posts_created ON app_feed_posts(created_at DESC);

-- ==================== footprints ====================
-- 足迹。
CREATE TABLE app_footprints_visits (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  country     TEXT NOT NULL DEFAULT '',
  city        TEXT NOT NULL DEFAULT '',
  visited_at  TEXT,
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_footprints_visits_visited ON app_footprints_visits(visited_at DESC);

-- ==================== games ====================
-- 游戏清单。
CREATE TABLE app_games_items (
  id            TEXT PRIMARY KEY,
  title         TEXT NOT NULL,
  platform      TEXT NOT NULL DEFAULT '',
  status        TEXT NOT NULL DEFAULT 'want',
  hours_played  INTEGER NOT NULL DEFAULT 0,
  rating        INTEGER NOT NULL DEFAULT 0,
  note          TEXT NOT NULL DEFAULT '',
  cover         TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_games_items_status ON app_games_items(status, created_at DESC);

-- ==================== goals ====================
-- 目标:打卡推进。
CREATE TABLE app_goals_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  target      INTEGER NOT NULL DEFAULT 0,
  progress    INTEGER NOT NULL DEFAULT 0,
  unit        TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'active',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_goals_items_status ON app_goals_items(status, created_at DESC);

-- ==================== health ====================
-- 健康:每天一条身体状态打卡。
CREATE TABLE app_health_entries (
  id          TEXT PRIMARY KEY,
  date        TEXT NOT NULL UNIQUE,
  weight_g    INTEGER,
  sleep_min   INTEGER,
  mood        TEXT NOT NULL DEFAULT '',
  exercise    TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_health_entries_date ON app_health_entries(date DESC);

-- ==================== ledger ====================
-- 记账:逐笔流水。amount 单位"分"避免浮点。
CREATE TABLE app_ledger_entries (
  id          TEXT PRIMARY KEY,
  type        TEXT NOT NULL DEFAULT 'expense',   -- 'expense' | 'income'
  amount      INTEGER NOT NULL,
  category    TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  happened_at TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_ledger_entries_happened ON app_ledger_entries(happened_at DESC, id DESC);
CREATE INDEX idx_app_ledger_entries_type_cat ON app_ledger_entries(type, category);

-- ==================== llms ====================
-- 大模型:在用的 LLM API key 配置。
CREATE TABLE app_llms_keys (
  id            TEXT PRIMARY KEY,
  provider      TEXT NOT NULL DEFAULT '',
  name          TEXT NOT NULL,
  api_key       TEXT NOT NULL DEFAULT '',
  base_url      TEXT NOT NULL DEFAULT '',
  default_model TEXT NOT NULL DEFAULT '',
  quota_note    TEXT NOT NULL DEFAULT '',
  note          TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== manuals ====================
-- 说明书:家电、设备的说明书 + 保修。
CREATE TABLE app_manuals_items (
  id              TEXT PRIMARY KEY,
  product_name    TEXT NOT NULL,
  brand           TEXT NOT NULL DEFAULT '',
  manual_url      TEXT NOT NULL DEFAULT '',
  purchased_at    TEXT,
  warranty_until  TEXT,
  note            TEXT NOT NULL DEFAULT '',
  cover           TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== medical ====================
-- 病例:就诊记录。
CREATE TABLE app_medical_records (
  id          TEXT PRIMARY KEY,
  date        TEXT NOT NULL,
  hospital    TEXT NOT NULL DEFAULT '',
  doctor      TEXT NOT NULL DEFAULT '',
  diagnosis   TEXT NOT NULL DEFAULT '',
  prescription TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_medical_records_date ON app_medical_records(date DESC);

-- ==================== memories ====================
-- 回忆:时间线式的日记本,每条对应一天。
CREATE TABLE app_memories_days (
  id          TEXT PRIMARY KEY,
  date        TEXT NOT NULL,
  location    TEXT NOT NULL DEFAULT '',
  weather     TEXT NOT NULL DEFAULT '',
  mood        TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_memories_days_date ON app_memories_days(date DESC);

-- ==================== movies ====================
-- Movies:想看 / 在看 / 看过的影片。
CREATE TABLE app_movies_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  year        INTEGER,
  status      TEXT NOT NULL DEFAULT 'want',
  rating      INTEGER NOT NULL DEFAULT 0,
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_movies_items_status_created ON app_movies_items(status, created_at DESC);

-- ==================== music ====================
-- Music:收藏的曲目。url 可指向 Spotify / YouTube / 网易云 等。
CREATE TABLE app_music_tracks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  artist      TEXT NOT NULL DEFAULT '',
  url         TEXT,
  cover       TEXT,
  note        TEXT NOT NULL DEFAULT '',
  rating      INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_music_tracks_created ON app_music_tracks(created_at DESC);

-- ==================== notes ====================
-- 笔记:无限嵌套笔记本 + 笔记。
CREATE TABLE app_notes_notebooks (
  id          TEXT PRIMARY KEY,
  parent_id   TEXT REFERENCES app_notes_notebooks(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  icon        TEXT,
  cover       TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_notes_notebooks_parent ON app_notes_notebooks(parent_id);

CREATE TABLE app_notes_pages (
  id           TEXT PRIMARY KEY,
  notebook_id  TEXT REFERENCES app_notes_notebooks(id) ON DELETE CASCADE,
  title        TEXT NOT NULL DEFAULT '',
  content      TEXT NOT NULL DEFAULT '',
  icon         TEXT,
  cover        TEXT,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at   TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_notes_pages_notebook ON app_notes_pages(notebook_id);

-- ==================== photos ====================
-- 影集:一张照片 + 文字。
CREATE TABLE app_photos_items (
  id          TEXT PRIMARY KEY,
  image_url   TEXT NOT NULL,
  caption     TEXT NOT NULL DEFAULT '',
  taken_at    TEXT,
  location    TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_photos_items_taken ON app_photos_items(taken_at DESC, created_at DESC);

-- ==================== profile ====================
-- 个人档:多 block 组成,每个 block 有标题 + 内容。
CREATE TABLE app_profile_blocks (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL DEFAULT '',
  content     TEXT NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_profile_blocks_sort ON app_profile_blocks(sort_order);

-- ==================== projects ====================
-- 个人项目(博客/副业/实验)。status ∈ { active, paused, done, abandoned }。
CREATE TABLE app_projects_items (
  id         TEXT PRIMARY KEY,
  title      TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'active',
  note       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_projects_items_status  ON app_projects_items(status);
CREATE INDEX idx_app_projects_items_created ON app_projects_items(created_at DESC);

-- ==================== prompts ====================
-- 指令集:常用 prompt 模板。
CREATE TABLE app_prompts_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  content     TEXT NOT NULL DEFAULT '',
  tags        TEXT NOT NULL DEFAULT '',
  model       TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== recipes ====================
-- 菜谱。
CREATE TABLE app_recipes_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  cuisine     TEXT NOT NULL DEFAULT '',
  servings    INTEGER NOT NULL DEFAULT 0,
  prep_min    INTEGER NOT NULL DEFAULT 0,
  ingredients TEXT NOT NULL DEFAULT '',
  steps       TEXT NOT NULL DEFAULT '',
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== resume ====================
-- 简历条目。kind ∈ { work, edu, project, skill, other }。
CREATE TABLE app_resume_entries (
  id          TEXT PRIMARY KEY,
  kind        TEXT NOT NULL DEFAULT 'work',
  title       TEXT NOT NULL,
  org         TEXT NOT NULL DEFAULT '',
  start_date  TEXT,
  end_date    TEXT,
  description TEXT NOT NULL DEFAULT '',
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_resume_entries_kind_sort ON app_resume_entries(kind, sort_order);

-- ==================== servers ====================
-- 服务器:在用的机器 / 主机 / Cloudflare Worker 等。
CREATE TABLE app_servers_machines (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  provider    TEXT NOT NULL DEFAULT '',
  host        TEXT NOT NULL DEFAULT '',
  ssh_port    INTEGER NOT NULL DEFAULT 22,
  ssh_user    TEXT NOT NULL DEFAULT '',
  ssh_key_note TEXT NOT NULL DEFAULT '',
  cost        INTEGER NOT NULL DEFAULT 0,
  cost_cycle  TEXT NOT NULL DEFAULT 'monthly',
  expire_at   TEXT,
  status      TEXT NOT NULL DEFAULT 'active',
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_servers_machines_status ON app_servers_machines(status, expire_at);

-- ==================== subs ====================
-- 订阅:Netflix / ChatGPT / 域名续费 等。amount 存"分"避免浮点。
CREATE TABLE app_subs_services (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  amount      INTEGER NOT NULL DEFAULT 0,
  cycle       TEXT NOT NULL DEFAULT 'monthly',     -- 'monthly' | 'yearly'
  next_charge TEXT,
  note        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_subs_services_next_charge ON app_subs_services(next_charge);

-- ==================== todos ====================
-- 待办:单层清单。
CREATE TABLE app_todos_items (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL DEFAULT '',
  done        INTEGER NOT NULL DEFAULT 0,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_todos_items_done ON app_todos_items(done, sort_order);

-- ==================== travel ====================
-- 旅行计划。status ∈ { planning, booked, done }。
CREATE TABLE app_travel_trips (
  id          TEXT PRIMARY KEY,
  destination TEXT NOT NULL,
  start_date  TEXT,
  end_date    TEXT,
  status      TEXT NOT NULL DEFAULT 'planning',
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_travel_trips_status ON app_travel_trips(status);
CREATE INDEX idx_app_travel_trips_start  ON app_travel_trips(start_date);

-- ==================== vault ====================
-- 密码箱:单机自部署,明文存储(用户已在自己的机器 + Cloudflare 账号下,这是设计选择)。
CREATE TABLE app_vault_entries (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  url        TEXT NOT NULL DEFAULT '',
  username   TEXT NOT NULL DEFAULT '',
  password   TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ==================== webs ====================
-- 网页:用户跟 AI 聊出来的 HTML demo / 小可视化,留着以后翻看。
CREATE TABLE app_webs_pages (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  html        TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_webs_pages_created ON app_webs_pages(created_at DESC);

-- ==================== wishlist ====================
-- 心愿单:想要的东西,带优先级和状态。
CREATE TABLE app_wishlist_items (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL DEFAULT '',
  price       INTEGER NOT NULL DEFAULT 0,        -- 单位"分"
  priority    TEXT NOT NULL DEFAULT 'normal',    -- 'high' | 'normal' | 'low'
  status      TEXT NOT NULL DEFAULT 'want',      -- 'want' | 'bought' | 'gave_up'
  note        TEXT NOT NULL DEFAULT '',
  cover       TEXT,
  created_at  TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_app_wishlist_items_status ON app_wishlist_items(status, priority);
