#!/usr/bin/env node
// 把 server/apps/<name>/schema.sql 合并成单一 mindbase.sql。
//
// 轻度约束:
//   - 如果一个应用的 schema 里有 app_<name>_* 表,那么里面**所有**表都必须用这个前缀(上下文应用)
//   - 如果一个应用的 schema 里没有任何 app_ 前缀表,那它属于系统应用,表名随意
//   - 混用 → 报错
//
// 这个规则给 AI 用:它 SELECT name FROM sqlite_master WHERE name LIKE 'app_%' 拿到的就是纯上下文。

import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const APPS_DIR = join(ROOT, 'server/apps')
const OUT      = join(ROOT, 'mindbase.sql')

const CT_RE = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_][A-Za-z0-9_]*)/gi

const collect = (dir) => {
  if (!existsSync(dir)) return { context: [], system: [] }
  const names = readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  const context = []
  const system  = []

  for (const name of names) {
    const file = join(dir, name, 'schema.sql')
    if (!existsSync(file)) continue
    const sql = readFileSync(file, 'utf8')
    const expected = `app_${name}_`

    const tables = [...sql.matchAll(CT_RE)].map((m) => m[1])
    if (tables.length === 0) continue

    const prefixed = tables.filter((t) => t.startsWith(expected))
    const bare     = tables.filter((t) => !t.startsWith('app_'))
    const wrong    = tables.filter((t) => t.startsWith('app_') && !t.startsWith(expected))

    if (wrong.length > 0) {
      throw new Error(
        `[schema] ${file}: 表 "${wrong[0]}" 用了别的应用的 app_ 前缀。应用 "${name}" 只能用 "${expected}*" 或裸表名。`
      )
    }

    if (prefixed.length > 0 && bare.length > 0) {
      throw new Error(
        `[schema] ${file}: 混用了带前缀("${prefixed[0]}")和裸表("${bare[0]}")。一个应用 schema 里要么全 app_${name}_*,要么全裸表(系统应用)。`
      )
    }

    const chunk = `-- ==================== ${name} ====================\n${sql.trim()}\n`
    if (prefixed.length > 0) context.push(chunk)
    else                     system.push(chunk)
  }

  return { context, system }
}

const { context, system } = collect(APPS_DIR)

const out = []
out.push('-- AUTO-GENERATED by scripts/build-schema.mjs')
out.push('-- 不要直接编辑;改 server/apps/<name>/schema.sql\n')

out.push('\n-- ============================================================')
out.push('-- 系统应用表 (无前缀)')
out.push('-- ============================================================\n')
out.push(...system)

out.push('\n-- ============================================================')
out.push('-- 上下文应用表 (app_<name>_*)')
out.push('-- ============================================================\n')
out.push(...context)

writeFileSync(OUT, out.join('\n'))
console.log(`✓ wrote ${OUT}  (context: ${context.length}, system: ${system.length})`)
